### ISSUE TITLE
Endpoints for custom kinds

### ISSUE THREAD

**Issue by djarotech** [cloud-ark/kubeprovenance#5]
To add endpoints for other kinds, make an addition to kind_compositions.yaml like the following:

- kind: Postgres
  plural: postgreses
  endpoint: apis/postgrescontroller.kubeplus/v1
  composition: [Pod, Service]

This will allow for the command below to work:
kubectl.sh get --raw /apis/kubeprovenance.cloudark.io/v1/namespaces/default/postgreses/client25/versions

**Comment by devdattakulkarni** [comment]
The kind_compositions file is used for registering the kubeprovenance endpoints. 

An alternative to using path parameters for defining provenance paths, is to use query parameters as done in Kubediscovery (https://github.com/cloud-ark/kubediscovery). One advantage of not using path parameters is that provenance retrieval will not be restricted by what is defined in kind_compositions file. In fact, we will be able to get rid of dependency on that file.

**Comment by devdattakulkarni** [comment]
Query parameters have been implemented.
